name: start AWS Step Functions execution
run-name: Start AWS Step Functions execution in ${{ inputs.environment }} | ${{ inputs.branch }}

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Git branch to deploy
        required: true
        default: main
        type: choice
        options:
          - main
          - lesson02
      environment:
        description: Target environment to deploy
        required: true
        default: dev
        type: choice
        options:
          - dev
          - sandbox

jobs:
  start-sfn:
    name: Start AWS Step Functions execution
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Start Step Functions execution
        run: |
          aws stepfunctions start-execution \
            --state-machine-arn arn:aws:states:ap-southeast-2:${{ secrets.AWS_ACCOUNT_ID }}:stateMachine:${{ inputs.environment }}-lesson02-state-machine \
            --name "execution-${{ github.run_id }}" \
            --input '{"branch": "${{ inputs.branch }}", "environment": "${{ inputs.environment }}"}'
